# NUMPY

-Numpy is a library developed to handle large, multi dimensional arrays, and matrices.
-it has a large collection of mathematicl functions
-Numpy is faster then python
-designed for efficient dta storage
-Numpy has uniformed datatypes instead of lists

Why is numpy faster than python:
-cause the numpy array is saved differently:
    In normal pythons the list are stored in random places in the RAM
    the Numpy arrays are stored sequentially - meaning the numbers in the array are stored one after another and not randomly

*The numpy array performs element by elemtent operations meaning if two arrays are addded they are not appended rather each element is added


In [1]:
import numpy as np

In [2]:
arr1= np.array([1,2,3,4,5]) #.array for creation of  array

arr2= np.array([4,6,32,44,51])

arr1+arr2

array([ 5,  8, 35, 48, 56])

In [26]:
np.zeros(5) #.zeros for a array with only 0s


array([0., 0., 0., 0., 0.])

In [4]:
np.ones(10) #.ones for a array with only 1s

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.linspace(0,100,10).astype(int) #gives linearly spaced values (intial start point, end point, linear spaces)

array([  0,  11,  22,  33,  44,  55,  66,  77,  88, 100])

In [6]:
np.eye(5,5) #generates a identitity matrix where only the diagonal is 1 rest  are 0s

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
np.random.rand(10) #prints random numbers specified between 0-1

array([0.39819675, 0.08939376, 0.79614312, 0.3512763 , 0.80729679,
       0.82225059, 0.48583931, 0.31715174, 0.92489714, 0.50703188])

In [8]:
(np.random.rand(100)<0.5) #shows values as true and false

array([ True,  True, False, False,  True,  True, False,  True,  True,
       False, False,  True, False,  True,  True, False,  True, False,
        True, False,  True,  True,  True,  True, False,  True, False,
       False,  True,  True, False,  True,  True, False, False, False,
        True, False,  True,  True, False, False, False,  True,  True,
       False,  True, False, False, False,  True,  True,  True,  True,
       False, False, False, False, False, False,  True,  True, False,
       False, False,  True,  True,  True, False,  True, False, False,
        True,  True, False, False, False, False, False, False, False,
        True,  True,  True, False,  True, False, False, False, False,
       False,  True, False,  True, False, False,  True, False,  True,
       False])

In [9]:
(np.random.rand(50) >0.5).sum() #the sum() shows the number of occurence

25

In [10]:
np.random.randint(1,7,10) #randint will print a random array from (specified start point which is icnluded, to end point not
                          #  included, and number of occurence) ex: (1(included),7(not included),10 (occurence))

array([2, 2, 1, 3, 2, 6, 1, 5, 2, 5])

In [11]:
np.random.randn(10) #used for standar deviation and stuff

array([-0.31090316, -0.60504289, -1.99388702, -0.52590748,  0.94580496,
        1.94767459, -1.06078669,  0.8450957 ,  1.88556429,  0.1072782 ])

In [12]:
mean1= np.random.randint(1,101,100)

In [13]:
np.mean(mean1)

44.41

In [14]:
np.median(mean1)

44.5

In [15]:
#operators: and= & ; or= | ; not = ~

In [16]:
#inbuilt functions:
#.min
#.max
#.exp
#.argmin - the index position of the smallest number
#.argmax - the index position of the largest number
#.sqrt

In [17]:
#axis=0 for rows, axis= 1 for coloumns

In [18]:
#.concatenate - joins sequence of array along thee axis
#.hsplit()- splits array in multiple sub arrays column wise horizonatallty
#.vsplit()- splits array in multiple sub arrays row wise vertically

In [19]:
a = np.array([[1,2,3],[0,1,4]]) 
print (a.size)

6


In [20]:
a = np.array([[1,2,3],[0,1,4]]) 
b = np.zeros((2,3), dtype=np.int16) 
c = np.ones((2,3), dtype=np.int16) 
d = a + b + c 
print (d[1,2] )

5


In [21]:
b = np.zeros((2,3), dtype=np.int16) 
print(b)

[[0 0 0]
 [0 0 0]]


In [22]:
a = np.array([[1,2,3],[0,1,4]]) 
print (a)

[[1 2 3]
 [0 1 4]]


In [23]:
c = np.ones((2,3), dtype=np.int16) 
print(c)

[[1 1 1]
 [1 1 1]]


In [24]:
a = np.array([[0, 1, 2], [3, 4, 5]]) 
b = a.sum(axis=1) 
print (b)

[ 3 12]


In [25]:
a = np.array([[0, 1, 2], [3, 4, 5]]) 
print(a)

[[0 1 2]
 [3 4 5]]
